[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
betting = "11111111111111111111111111111111"

[programs.devnet]
betting = "11111111111111111111111111111111"

[programs.mainnet]
betting = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "custom"
wallet = "~/.config/solana/id.json"

[provider.custom]
url = "https://fragrant-orbital-road.solana-devnet.quiknode.pro/ba431041d0ed9de5c4535123b41648fc39385a89/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "spl_token.so"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "spl_associated_token_account.so"
